theme = "onedarkerer"
# theme = "flexoki_dark"
# theme = "onedarker"
# theme = "everblush"
# theme = "adwaita-dark"
# theme = "gruvbox_dark_hard"
# theme = "iroaseta"
# theme = "jellybeans"
# theme = "jetbrains_dark"
# theme = "molokai"

[editor]
color-modes = true
end-of-line-diagnostics = "hint"
trim-trailing-whitespace = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = false

[keys.insert]
"§" = "normal_mode"

[keys.normal]
"C-r" = ":reload-all"

[keys.normal.f]
c = ":buffer-close"
q = ":quit"
r = ":reload"
R = ":reload-all"
s = ":toggle soft-wrap.enable"
w = ":write"

